### ISSUE TITLE
Connect requests can stall on Windows 10

### ISSUE THREAD

**Issue by grouma** [dart-lang/sse#16]
See for initial details: https://github.com/dart-lang/webdev/issues/766

**Comment by anik786** [comment]
I had a related issue with Flutter web and connecting with sse and found that it was just an issue with Kaspersky anti-virus.

I just went on Kaspersky > Settings> Protection > Web Anti-Virus > Advanced Settings> Configure Trusted Urls > Add.

For web address I just added localhost and problem solves.

**Comment by grouma** [comment]
Thanks for the details. I opened this issue on behalf of another user but never was able to reproduce it myself. Closing this issue but hopefully your advice can help others.

**Comment by alexander-doroshko** [comment]
@grouma I can confirm that disabling Kaspersky Free Antivirus solves the problem for me as well!

Given that the intersection of Dart and Kaspersky users is probably much higher than me and Yahya, you might want to investigate why `webdev serve --debug` works just fine with Kaspersky enabled but `webdev daemon` - doesn't work until you edit and save any file.
