### ISSUE TITLE
Support transparent re-connects on the server side

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sse#18]
#17 added retry logic to the client, but as far as the server sees this is a new `SseConnection` client connection and the old `SseConnection` stream completes.

In dwds, the connection closing triggers the services shutting down:

https://github.com/dart-lang/webdev/blob/2958ede70f20c402e869b4169f3d2f97162e51d4/dwds/lib/src/handlers/dev_handler.dart#L186-L194

It would be nice if the server was able to handle reconnects (within some time period, and opted-in) transparently so the connection never closes and the streams on `SseConnection` are automatically connected/proxied to the new connection.

**Comment by DanTup** [comment]
@grouma thanks for merging and releasing! I'd like to update dwds with this - do you have a preference for how it's used - should it be passed in (eg. by Flutter) and default to null (current behaviour), or should dwds default to some timeout (a change in behaviour, but maybe a good one)? If the latter, should the timeout be overridable (eg. by Flutter) and what would you be happy with as a default timeout?

When testing on GitPod, I was using 30s timeouts in these locations:

- https://github.com/dart-lang/webdev/compare/master...DanTup:vscode-testing#diff-87313797d9df914d03f07789c52010cfR40
- https://github.com/dart-lang/webdev/compare/master...DanTup:vscode-testing#diff-0fdc943e6f1b69c04649e442f7ae5b48R15

**Comment by grouma** [comment]
I don't see any harm just setting a default value in DWDS itself. I don't see the need for making the value configurable.
