### ISSUE TITLE
Sse_Handler shouldn't run jsonEncode before adding payload to the sink

### ISSUE THREAD

**Issue by eflat64** [dart-lang/sse#53]
I am currently using the dart sse package for a project that I am working on, and I have noticed that when the payload is added to the sink, a jsonEncode is performed to "to escape new lines".

https://github.com/dart-lang/sse/blob/31816f2c03fefc48c9c55f4f7124836a04679cc0/lib/src/server/sse_handler.dart#L96-L97

However, I'm not sure that this is the most desirable way to do this as it is not always against SSE spec to have a data line without enclosing quotes - especially if it is valid json. For example, in the case below of parsing a String of valid json, the result is that the receiving end would need to do a double jsonDecode to get the map (the first to remove the quotes, and the second to actually process the json).

Server which sends a string of valid json to listeners.
```
void main() async {
  var json = '{"foo" : "bar"}';
  var handler = SseHandler(Uri.parse('/sseHandler'));
  await io.serve(handler.handler, '0.0.0.0', 7070);
  var connections = handler.connections;
  while (await connections.hasNext) {
    var connection = await connections.next;
    connection.sink.add(json);
  }
}
```

Client which receives sse payload from the server upon connection.
```
void main() async {
  final client = await EventSource.connect(
    Uri(
      scheme: 'http',
      host: '0.0.0.0',
      port: 7070,
      path: '/sseHandler',
    ),
  );

  client.listen(
    (event) {
      if (event.data != null) {
        try {
          // Will fail
          Map<String, String> json = jsonDecode(event.data!);
        } catch (e) {
          print(e);
        }
      }
    },
  );
}
```
The client runs with the output
`Type 'String' is not a subtype of type 'Map<String, String>'`

Although running jsonEncode does escape the new lines,  it also has other repercussion which are not always desired, such as in the case above where the payload is wrapped in double quotes. Might I suggest that another method is used to escape new lines?

**Comment by grouma** [comment]
The `SeeHandler` is intended to be used with the client in this package. We handle the decoding [here](https://github.com/dart-lang/sse/blob/31816f2c03fefc48c9c55f4f7124836a04679cc0/lib/client/sse_client.dart#L117). There's also additional logic built on top of the protocol making a vanilla use of `EventSource` and `SseHandler` not possible.

**Comment by eflat64** [comment]
Unless this sse package has a more specific purpose which requires a matching server and client, I don't see why it has been limited in this way.

What additional logic has been built on top of the protocol? As one of the most popular dart sse packages, nevermind one of the very few that actually allows the server side implementation, I would've thought that the transmission of each SSE should just be correct, capable of being picked up by any SSE client. What if someone's client was written in a different programming language? 

In addition, your answer doesn't explain why a JSON-specific method is being used to perform an expressly non-JSON task (commented as for just removing multi line). If that's the only action needed to be done, surely a simple `.replaceAll()` would work, instead of all the other unnecessary logic that comes with `jsonEncode()`.

**Comment by grouma** [comment]
> Unless this sse package has a more specific purpose which requires a matching server and client, I don't see why it has been limited in this way.
> 

The intent behind this package is to be a drop in replacement for Websockets where Websockets may not be supported. The API is modeled after Dart's Websocket API and it supports bidirectional communication. The server has implicit assumptions on the client such as the [clientId](https://github.com/dart-lang/sse/blob/9084339389eb441d0c0518cddac211a097e78657/lib/src/server/sse_handler.dart#L219).

> What additional logic has been built on top of the protocol? As one of the most popular dart sse packages, nevermind one of the very few that actually allows the server side implementation, I would've thought that the transmission of each SSE should just be correct, capable of being picked up by any SSE client. What if someone's client was written in a different programming language?
> 

See above. This is not a current goal of the package. I can sympathize that the package name is somewhat of a misnomer as it offers additional logic on top of a vanilla SSE connection. You are free to fork the package or potentially provide a new top level backend without the assumptions. I'm happy to review PRs.

> In addition, your answer doesn't explain why a JSON-specific method is being used to perform an expressly non-JSON task (commented as for just removing multi line). If that's the only action needed to be done, surely a simple `.replaceAll()` would work, instead of all the other unnecessary logic that comes with `jsonEncode()`.

You are right that it's serving a non-JSON task. If we were to change to a `replaceAll` approach we'd need to ensure that we could add back the newlines on the other end. That can easily be done but I suppose at the time of implementation the `jsonEncode` was the easiest way to do that. 

Note again, the intent behind this package is to have an API that has a direct mapping to the websockets API. We want to support a simple `sink` / `stream` on both the client and server. We should be able to pass data on the `sink` which contains newlines and be able to retrieve it on the other end in a single message.
